types={
    wall:[
        {layer:1},
        {layer:1},
        {layer:1},
        {layer:1},
        {layer:0},
        {layer:1},
        {layer:0},
        {layer:0},
        {layer:0},
        {layer:1},
        {layer:0},
        {layer:1},
        {layer:0},
    ],
}
stage={scale:0,focus:{x:0,y:0,scale:0},scene:'level'}
game={zone:27,edge:{x:0,y:0},tileSize:30,check:{x:0,y:0,zone:0,gravity:1},position:{x:0,y:0},edgePosition:{x:17,y:17},firstGen:0}
physics={gravity:1.2,resistance:0.1,friction:0}
graphics={main:0,backgrounds:[],minor:[]}
transition={trigger:false,anim:0,scene:stage.scene,mode:0,direction:0}
inputs={mouse:{x:0,y:0},rel:{x:0,y:0},keys:[[false,false,false,false],[false,false,false,false]]}
entities={clouds:[],walls:[[],[]],enemies:[],players:[],particles:[]}
collision={incident:{x:0,y:0},calculate:{x:0,y:0}}
run={back:[],fore:[],info:[]}
_=0